@startuml

skinparam monochrome false
skinparam shadowing false
skinparam ParticipantPadding 95
'title Message Style - Sequence Diagram


storage root #white
storage "Loc: RU" as RU #lightgreen
storage "Loc: EU" as EU #lightgreen
storage "Loc: US" as US  #white

' storage "Store: HDD" as HDD 
storage "Storage: SSD" as SSD  #khaki

storage "City: Milan" as City #lightgreen

storage root #white

storage "Node 1" as N1 #white
storage "Node 2" as N2  #white
storage "Node 3" as N3 #white
storage "Node 4" as N4  #lightgreen
storage "Node 5" as N5  #lightgreen
storage "Node 6" as N6  #lightgreen
storage "Node 7" as N7 #white
storage "Node 8" as N8  #lightgreen
storage "Node 9" as N9 #lightgreen
storage "Node 10" as N10  #lightgreen

root -down-> RU  #black
root -down-> EU #black
root -down-> US  #black

' root -down-> HDD
root -down-> SSD #black


EU -down-> City #black

City -down-> N3 #black
City -down-> N4 #black
City -down-> N5 #black
City -down-> N6 #black

RU --down-> N7 #black
RU --down-> N8 #black
RU --down-> N9 #black
RU --down-> N10 #black


US --down-> N1 #black
US --down-> N2 #black


' HDD --down-> N1
' HDD --down-> N3
' HDD --down-> N5
' HDD --down-> N7
' HDD --down-> N9
SSD --down-> N2 #black
SSD --down-> N4 #darkgoldenrod
SSD --down-> N5 #darkgoldenrod
SSD --down-> N6 #darkgoldenrod
SSD --down-> N8 #darkgoldenrod
SSD --down-> N9 #darkgoldenrod
SSD --down-> N10 #darkgoldenrod

N1 -[hidden]right-> N2
N2 -[hidden]right-> N3
N3 -[hidden]right-> N4
N4 -[hidden]right-> N5
N5 -[hidden]right-> N6
N6 -[hidden]right-> N7
N7 -[hidden]right-> N8
N8 -[hidden]right-> N9
N9 -[hidden]right-> N10


' SSD -[hidden]right-> HDD


@enduml
