@startuml

skinparam monochrome false
skinparam shadowing false
skinparam ParticipantPadding 95
'title Message Style - Sequence Diagram


storage root  #darkgoldenrod
storage "Loc: RU" as RU #khaki
storage "Loc: EU" as EU #khaki
storage "Loc: US" as US  #white

' storage "Store: HDD" as HDD 
storage "Storage: SSD" as SSD  #lightgreen

storage "City: Milan" as City  #khaki

storage root  #khaki

storage "Node 1" as N1 #white
storage "Node 2" as N2  #white
storage "Node 3" as N3  #khaki
storage "Node 4" as N4  #lightgreen
storage "Node 5" as N5  #lightgreen
storage "Node 6" as N6  #lightgreen
storage "Node 7" as N7  #khaki
storage "Node 8" as N8  #lightgreen
storage "Node 9" as N9 #lightgreen
storage "Node 10" as N10  #lightgreen

root -down-> RU  #darkgoldenrod
root -down-> EU #darkgoldenrod
root -down-> US  #black

' root -down-> HDD
root -down-> SSD #black


EU -down-> City #darkgoldenrod

City -down-> N3 #darkgoldenrod
City -down-> N4 #darkgoldenrod
City -down-> N5 #darkgoldenrod
City -down-> N6 #darkgoldenrod

RU --down-> N7 #darkgoldenrod
RU --down-> N8 #darkgoldenrod
RU --down-> N9 #darkgoldenrod
RU --down-> N10 #darkgoldenrod


US --down-> N1 #black
US --down-> N2 #black


' HDD --down-> N1
' HDD --down-> N3
' HDD --down-> N5
' HDD --down-> N7
' HDD --down-> N9
SSD --down-> N2 #black
SSD --down-> N4 #darkgreen
SSD --down-> N5 #darkgreen
SSD --down-> N6 #darkgreen
SSD --down-> N8 #darkgreen
SSD --down-> N9 #darkgreen
SSD --down-> N10 #darkgreen

N1 -[hidden]right-> N2
N2 -[hidden]right-> N3
N3 -[hidden]right-> N4
N4 -[hidden]right-> N5
N5 -[hidden]right-> N6
N6 -[hidden]right-> N7
N7 -[hidden]right-> N8
N8 -[hidden]right-> N9
N9 -[hidden]right-> N10


' SSD -[hidden]right-> HDD


@enduml
